title: "Jacob Davidsen"
description: "Associate Professor at Aalborg University"
url: "https://jdavidsen.github.io"
theme: minima

author:
  name: "Jacob Davidsen"
  avatar: "/assets/images/profile.png"
  bio: "Researcher in collaboration in digital contexts"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
