title: "Jacob Davidsen"
description: "Associate Professor at Aalborg University"
url: "https://jdavidsen.github.io"
theme: minima

author:
  name: "Jesper Davidsen"
  avatar: "/assets/images/profile.jpg"
  bio: "Researcher in classroom interaction, technology, and education"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
